version:"2.0"
services:
  mthc-core:
    build: mthc-core
    environments:
      MTHC_LOOP_NUM: 100
      MTHC_CONCURRENT_NUM: 1000
      MTHC_CONNECTION_LIMIT: 10
      Logging:LogLevel:Microsoft: None
    command: ["dotnet","/bin/mthc/UsingHttpClientConcurrentCore.dll","2"]
  mthc-net:
    build: mthc-net
    environments:
      MTHC_LOOP_NUM: 100
      MTHC_CONCURRENT_NUM: 1000
      MTHC_CONNECTION_LIMIT: 10
    command: ["mono","/bin/mthc/UsingHttpClientConcurrentCore.exe","2"]
    