version: "2.0"
services:
  mthc-core:
    build:
      context: mthc-core
      args:
        http_proxy: $DOCKER_HTTP_PROXY
    environment:
      MTHC_LOOP_NUM: 10
      MTHC_CONCURRENT_NUM: 100
      MTHC_CONNECTION_LIMIT: 10
      Logging:LogLevel:Microsoft: None
    command: ["bash","test.sh"]
  mthc-net:
    build:
      context: mthc-net
      args:
        http_proxy: $DOCKER_HTTP_PROXY
    environment:
      MTHC_LOOP_NUM: 10
      MTHC_CONCURRENT_NUM: 100
      MTHC_CONNECTION_LIMIT: 10
    command: ["bash","test.sh"]
    